language: scala
dist: trusty
sudo: false
jdk: oraclejdk8
script:
- sbt scalafmtTest ^scripted
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
